FROM alpine:3.20

RUN apk add --no-cache \
    bash \
    iputils \
    iproute2 \
    arp-scan \
    curl \
    ca-certificates \
    bind-tools \
    jq \
    && update-ca-certificates

COPY ipv6ddns /usr/local/bin/ipv6ddns

ENTRYPOINT ["ipv6ddns"]
